# Generated by Django 3.2.13 on 2023-05-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_profile',
            name='perimgpath',
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath1',
            field=models.ImageField(blank=True, db_column='FaceImgPath1', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath2',
            field=models.ImageField(blank=True, db_column='FaceImgPath2', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath3',
            field=models.ImageField(blank=True, db_column='FaceImgPath3', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath4',
            field=models.ImageField(blank=True, db_column='FaceImgPath4', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath5',
            field=models.ImageField(blank=True, db_column='FaceImgPath5', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath6',
            field=models.ImageField(blank=True, db_column='FaceImgPath6', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath7',
            field=models.ImageField(blank=True, db_column='FaceImgPath7', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='faceimages',
            name='faceimgpath8',
            field=models.ImageField(blank=True, db_column='FaceImgPath8', null=True, upload_to='images/'),
        ),
    ]
